# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='姓名')),
                ('email', models.EmailField(default='', max_length=64, verbose_name='邮箱')),
                ('position', models.CharField(default='', max_length=256, verbose_name='职位')),
                ('company', models.CharField(default='', max_length=128, verbose_name='公司')),
                ('website', models.CharField(max_length=512, null=True, verbose_name='网站')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='手机号码')),
                ('sex', models.CharField(default='', max_length=32, verbose_name='性别')),
                ('birthday', models.CharField(default='', max_length=128, verbose_name='出生年月')),
            ],
            options={
                'verbose_name': '名片',
                'verbose_name_plural': '名片',
            },
        ),
    ]
